services:
  transaction_importer:
    #image: transaction_importer_spring
    build: .
    container_name: transaction_importer_spring
    environment:
      #- SPRING_DATASOURCE_URL=jdbc://
      #- SPRING_DATASOURCE_USERNAME=
      #- SPRING_DATASOURCE_PASSWORD=
      #- MAIL_USERNAME=
      #- MAIL_PASSWORD=
      #- MAIL_LABEL=
      #- SERVER_PORT=8080
      - EXAMPLE=
    restart: unless-stopped
    ports:
      - 8180:8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.transaction_importer_spring.rule=Host(`transaction-importer-spring.$MY_DOMAIN`)"
      - "traefik.http.services.transaction_importer_spring.loadbalancer.server.port=8080"
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true

