services:
  transaction_importer:
    image: transaction_importer
    container_name: transaction_importer
    environment:
      - SPRING_DATASOURCE_URL=jdbc://
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_LABEL=
      - SERVER_PORT=8080
    ports:
      - 8080:8080
