{
 "title": "Financial Transactions",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_MYSQL", "query": "mysql" },
   { "name": "Category", "query": "select name from category;" }
  ]
 },
 "panels": [
  { "title": "Finance Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT\n  date AS \"time\",\n  description,\n  transaction_type,\n  -(amount) as debit\nFROM transaction\nJOIN category ON transaction.category_id = category.id\nwhere transaction_type = 'debit'\nand category.name like $Category \nAND $__timeFilter(date)\nORDER BY date"
    },
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT\n  date AS \"time\",\n  description,\n  transaction_type,\n  amount as credit\nFROM transaction\nwhere transaction_type = 'credit'\nAND $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Net Worth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT\r\nSUM(IF(account.type = 'mortgage' OR account.type = 'credit card', -account.balance, account.balance)) \"Net Worth\"\r\nfrom account\r\nJOIN institution ON account.institution_id = institution.id"
    }
   ]
  },
  {
   "title": "Income Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT \namount as \"Amount\"\nfrom transaction\nJOIN category ON transaction.category_id = category.id\nwhere $__timeFilter(date)\nand transaction_type = 'credit'\nand (category.name = 'Income'\nor category.parent_id = 71)\nand category.name like $Category "
    }
   ]
  },
  {
   "title": "Spend Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT \namount as \"Amount\"\nfrom transaction\nJOIN category ON transaction.category_id = category.id\nwhere $__timeFilter(date)\nand transaction_type = 'debit'\nand category.name != 'Transfer'\nand category.name != 'Credit Card Payment'\nand category.name like $Category "
    }
   ]
  },
  {
   "title": "Net Worth Without House",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT\r\nSUM(IF(account.type = 'mortgage' OR account.type = 'credit card', -account.balance, account.balance)) \"Net Worth\"\r\nfrom account\r\nJOIN institution ON account.institution_id = institution.id\r\nwhere account.type != 'property'"
    }
   ]
  },
  { "title": "Finance Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Spending Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT \ndate as \"time\",\n-(amount) as \"Amount\",\ndescription as Description,\naccount.name \"Account Name\",\ncategory.name as \"Category\",\ninstitution.name \"Institution\"\nfrom transaction\nJOIN vendor ON transaction.vendor_id = vendor.id\nJOIN account ON transaction.account_id = account.id\nJOIN institution ON account.institution_id = institution.id\nJOIN category ON transaction.category_id = category.id\nwhere $__timeFilter(date)\nand transaction_type IN('debit', 'Debit')\nand category.name != 'Transfer'\nand category.name like $Category \norder by date desc"
    }
   ]
  },
  {
   "title": "Income Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT \ndate as \"time\",\namount as \"Amount\",\ndescription as Description,\n#vendor.name as \"Merchant\",\naccount.name \"Account Name\",\ncategory.name \"Category\",\ninstitution.name \"Institution\"\nfrom transaction\nJOIN vendor ON transaction.vendor_id = vendor.id\nJOIN account ON transaction.account_id = account.id\nJOIN institution ON account.institution_id = institution.id\nJOIN category ON transaction.category_id = category.id\nwhere $__timeFilter(date)\nand (category.name = 'Income' OR category.parent_id = 71)\nand category.name like $Category\norder by date desc"
    }
   ]
  },
  {
   "title": "Total Spent by Category",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT \n  category.name AS \"Category\",\n  sum(\n    if(transaction_type = 'debit', -(amount), amount)\n    ) as \"Total\"\nfrom transaction\nJOIN category ON transaction.category_id = category.id\nwhere $__timeFilter(date)\nand transaction.transaction_type in ('debit', 'Debit')\nand category.name like $Category\nGROUP BY category.name\norder by amount desc"
    }
   ]
  },
  {
   "title": "Total Spent at Merchant",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT \n  date as \"time\",\n  sum(\n    if(transaction_type = 'debit', -(amount), amount)\n    ) as \"Total\",\n  vendor.name AS \"Merchant\"\nfrom transaction\n  JOIN vendor ON transaction.vendor_id = vendor.id\n  JOIN category ON transaction.category_id = category.id\nwhere $__timeFilter(date)\nand transaction.transaction_type in ('debit', 'Debit')\nand category.name like $Category \nGROUP BY vendor.name\norder by amount desc"
    }
   ]
  },
  {
   "title": "Account Balances",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT\r\naccount.name \"Account Name\",\r\nIF(account.type = 'mortgage' OR account.type = 'credit card', -account.balance, account.balance) \"Balance\",\r\naccount.type \"Type\",\r\ninstitution.name \"Institution\",\r\naccount.last_updated \"Last Updated\"\r\nfrom account\r\nJOIN institution ON account.institution_id = institution.id\r\norder by account.name "
    }
   ]
  },
  {
   "title": "Share of Category Purchases",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "select\n    Category,\n    Total\nfrom (\nSELECT category.name AS \"Category\",\n             sum(amount)             as \"Total\"\n      from transaction\n               JOIN category ON transaction.category_id = category.id\n      where transaction.date > now() - interval 1 month\n        AND transaction.transaction_type IN ('debit', 'Debit')\n        AND category.name != 'Transfer'\n        AND category.name != 'Credit Card Payment'\n      GROUP BY category.name) tmp\norder by Total desc\n"
    }
   ]
  },
  {
   "title": "Unknown Category Purchases",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "transaction_importer",
     "rawSql": "SELECT \n  date as \"time\",\n  description as \"Description\",\n  amount as \"Amount\"\nfrom transaction\n  JOIN category ON category.id = transaction.category_id\nwhere $__timeFilter(date)\nAND category.name = 'Unknown'"
    }
   ]
  }
 ]
}